### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by faibistes** [enqueue/metabase#2]
After compiling the clickhouse_module2 branch and starting the uberjar, I only get  blank page on localhost:3000

**Comment by enqueue** [comment]
Hi faibistes! Great that you want to try out the experimental ClickHouse driver! I am very much looking forward to learning about your experiences.

I just cloned into a fresh directory and compiled (this takes very long). Did you follow these steps?

* bin/build no-translations (takes _very_ long)
* java -jar target/uberjar/metabase.jar

What is the output in your console?

I actually do not want to distribute the fork as binary, but if you are still struggling with the build environment, you can download the jar file I just used from the Releases page [here](https://github.com/enqueue/metabase/releases/tag/0.0.1-experimental).

**Comment by faibistes** [comment]
I had compiled it without no-translations. I'm building it with no-translations right now. If it doesn't work, I'll let you know so you can send me the jar

**Comment by faibistes** [comment]
Log: [https://gist.github.com/faibistes/4e286bd202246d8f3bbbb2e7f731a26a#file-gistfile1-txt](url)
After building with -no-translations, I still get a blank page :-(

**Comment by enqueue** [comment]
Your log looks fine, so the backend is probably running. Anyways, I uploaded the current branch version for you to test: https://1drv.ms/u/s!AjdhfuliZEqTnHyQr5EjauVcavAA I just tested it in my `/tmp` directory, and http://localhost:3000 greeted me with the initial setup screen.

**Comment by faibistes** [comment]
I have tried your uberjar and it works. There are some quirks here and there (well, in fact, quite a lot) but it's usable

**Comment by enqueue** [comment]
Thanks for the feedback @faibistes ! That's good news. Please let me know about any driver related issue you encounter, or even create a PR, preferrably in the new reposity for the modular driver, enqueue/metabase-clickhouse-driver
