### ISSUE TITLE
Additional JDBC connection string options

### ISSUE THREAD

**Issue by TyShkan** [enqueue/metabase#3]
Hi @enqueue, great job, thanks!

I compiled the branch and ran some tests with local ClickHouse installation. It seems like database configuration doesn't work with any params within "Additional JDBC connection string options". Every time I put anything in the field I'm receiving error "java.lang.IllegalArgumentException: port is missed or wrong".

**Comment by enqueue** [comment]
Hi @TyShkan thanks for trying out the driver. I will try to fix this now.

**Comment by TyShkan** [comment]
Still receiving the same issue:

<img width="200" alt="Screenshot 2019-03-12 02 34 59" src="https://user-images.githubusercontent.com/39046/54164895-8716fc80-446f-11e9-84f8-b497e1e74715.png">

Also tried "sessionTimeout=42" value. No luck :dizzy_face:

**Comment by enqueue** [comment]
Hi, sorry you are still get this error. Have you updated the driver in the plugins directory? I notice that you set the port to 8443, are you using SSL by any chance?

![Screenshot_20190312_072854](https://user-images.githubusercontent.com/5407006/54179300-ab3b0380-4498-11e9-806e-7065d35d9bbd.png)

**Comment by TyShkan** [comment]
Hi, sorry, my bad. I was not cleaned up ~/Library/Application Support/Metabase/Plugins/ directory before using updated metabase.jar.

Yes, I'm using SSL connection.

Everything works fine, thanks!

**Comment by enqueue** [comment]
Have fun and please report any further issues.
